---
# install rdiff-backup under CentOS

- name: CentOS | install necessary pre-requisite packages
  yum:
    name: "{{ rdiffbackup_necessary_packages[ansible_distribution + ansible_distribution_major_version] }}"
    state: "{{ rdiffbackup_package_state }}"
  become: true

- name: CentOS | enable Frank's COPR repo
  command: yum --assumeyes copr enable frankcrawford/rdiff-backup
  args:
    warn: false  # to avoid warning to use yum or dnf module
  become: true

- name: CentOS | install rdiff-backup
  yum:
    name: rdiff-backup
    state: "{{ rdiffbackup_package_state }}"
  become: true

- name: CentOS | install optional dependencies if requested
  yum:
    name: "{{ rdiffbackup_optional_packages[ansible_distribution + ansible_distribution_major_version] }}"
    # we need the powertools repo to install pyxattr
    enablerepo: "{{ (ansible_distribution_major_version | int >= 8) | ternary('powertools', omit) }}"
    update_cache: "{{ ansible_distribution_major_version | int >= 8 }}"
    state: "{{ rdiffbackup_package_state }}"
  when: rdiffbackup_install_optional
  become: true
