galaxy_info:
  author: Eric Lavarde
  description: rdiff-backup lead developer
  company: rdiff-backup open source project

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # Choose a valid license ID from https://spdx.org - some suggested licenses:
  # - BSD-3-Clause (default)
  # - MIT
  # - GPL-2.0-or-later
  # - GPL-3.0-only
  # - Apache-2.0
  # - CC-BY-4.0
  license: MIT

  min_ansible_version: 2.9

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
  - name: Fedora
    versions:
    - 31
    - 32
    - 33
  - name: EL  # CentOS has been tested, not yet RHEL
    versions:
    - 7
    - 8
  - name: Debian
    versions:
    - bullseye  # 11
    - sid  # unstable
  - name: Ubuntu
    versions:
    - focal  # 20.04
    - groovy  # 20.10
    - hirsute  # 21.04
  - name: Windows
    - 2019
    - 10

  galaxy_tags: [backup, linux, system]
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
